#variables
counter = 9
list_counter = 1
numbers = []
answers_words = []
times_answered = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
english11_20 = ['eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty']
maori11_20 = ['tekau ma tahi', 'tekau ma rua', 'tekau ma toru', 'tekau ma wha', 'tekau ma rima', 'tekau ma ono', 'tekau ma whitu', 'tekau ma waru', 'tekau ma iwa', 'rua tekau']
#if 1 is pressed it will go to the maori to english translation, vice versa if 2 is pressed
print('Welcome to the māori number quiz from 11-20')
print('Press 1 if you want the māori question and for you to answer in english')
print('Press 2 if you want the english question and for you to answer in māori')
decider = int(input('Enter option:  '))
if decider == 1:
    numbers = maori11_20
    answers_words = english11_20
elif decider == 2:
    numbers = english11_20
    answers_words = maori11_20
else:
    print('Please enter a valid integer')
    #while the counter variable isn't 0, this will keep looping
    while counter != 0:
        #random number generator
        answer_generator = random.randint(0, counter)
        #the question and answer will be generated by the generator
        question = numbers[answer_generator]
        answer = answers_words[answer_generator]
        print(question)
        #the user asks the question h
        user = input('Enter english answer:  ')
        #if the user's answer matches up with the variable answer, the program will print it as 'correct' otherwise it will print it as 'wrong'
        if user == answer:
            print('Correct')
            times_answered[answer_generator] += 1
            print('')
            if times_answered[answer_generator] == 3:
                numbers.remove(question)
                answers_words.remove(answer)
                times_answered.remove(3)         
                counter -= 1
                print('')
        elif user != answer:
            print(f'{question} is actually {answer} ')
            print('')
            time.sleep(2)
